"""Telemetry-module tamper evidence.

What this is
------------
A build-time manifest of sha256 hashes for every file in
`profine/telemetry/`. At import time we recompute the hashes of the
currently-loaded files and compare. A mismatch emits a single warning
line to stderr — it does NOT refuse to run.

What this is NOT
----------------
Tamper *prevention*. We can't stop anyone with Apache 2.0 source from
modifying these files; that's the price of open source. What we can
do is make a modification visible: anyone running modified code sees
a warning printed to stderr on every invocation, and a future
backend can correlate the manifest hash in their telemetry payload
to identify modified clients.

Two assumptions
---------------
1. `MANIFEST` is regenerated by `scripts/rebuild_telemetry_manifest.py`
   before each release. The manifest is committed; PRs that change
   telemetry files MUST regenerate it (and the CI sync check verifies).
2. The verifier itself is removable. A determined modifier patches
   this file too. That's fine — the goal is *evidence*, not control.

Performance
-----------
We hash files once per process at import time (~1ms for the whole
module). Result is cached on the module object; subsequent imports
no-op.
"""

from __future__ import annotations

import hashlib
import os
import sys
from pathlib import Path
from typing import Final


# ---- BEGIN GENERATED MANIFEST (DO NOT EDIT BY HAND) ----
# Regenerate with: python3 scripts/rebuild_telemetry_manifest.py
# Each entry: filename (relative to profine/telemetry/) → sha256 of file bytes
MANIFEST: Final[dict[str, str]] = {
    "__init__.py": "9dcb80519dd36de0d637a5b66f38b92057db64f8bf94861274bc02596214c271",
    "agent_priors.py": "baa62d32d42e618d23477c5ed5acdb703b5fb6bb5fc8538393a762bde96ec5ff",
    "builder.py": "95125f663badc008eec68487da8deadecf0cb7f851bc29587fa59a425c8018c9",
    "consent.py": "55f9dfbf0123f72ec502992ac2a3e5a5fcffad4180f065840da443057b3f353b",
    "crash_class.py": "cd0394f0d12045e51da2a0d929df58cb25fb388aa51e3b95fde04376d4af8ecb",
    "emit.py": "01d8623f69fcd7772898b7cadc355c87e96104e2b2427580dfc19dbe57234311",
    "fields.py": "130514e10372a6759907d94a132f1b17df74c386cbbdb060b895eeb2319be460",
    "fingerprint.py": "22c337757717501a2024f3c612650200138c79c788d24d2bd2d9b54405c27510",
    "priors.py": "6efe4ba19d6a64e01b3ad62eed67c43b504f6d8218f93d04b5cb177e46db7c1c",
    "recorder.py": "9fab03b1adfe25e667b77c55937575e3fd20de2902893cc6747f861bfbd6ed0d",
}
# ---- END GENERATED MANIFEST ----


# Set this to skip the check entirely (used in tests).
_DISABLE_ENV_VAR = "PROFINE_DISABLE_INTEGRITY_CHECK"


def _telemetry_dir() -> Path:
    return Path(__file__).resolve().parent


def _hash_file(path: Path) -> str | None:
    """sha256 of file bytes; None if file is missing."""
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return None


def verify_integrity() -> list[str]:
    """Compare on-disk file hashes to the baked manifest.

    Returns a list of human-readable mismatch descriptions. Empty list
    means "everything matches the manifest" (or "no manifest set; skip").
    """
    if not MANIFEST:
        # No manifest baked in — skip check (dev builds or unbuilt source).
        return []

    if os.environ.get(_DISABLE_ENV_VAR, "").strip().lower() in ("1", "true", "yes", "on"):
        return []

    mismatches: list[str] = []
    base = _telemetry_dir()

    # Check declared files
    for relname, expected in MANIFEST.items():
        path = base / relname
        actual = _hash_file(path)
        if actual is None:
            mismatches.append(f"  MISSING  {relname}")
        elif actual != expected:
            mismatches.append(f"  MODIFIED {relname}  (expected {expected[:12]}..., got {actual[:12]}...)")

    # Detect files we didn't expect (could be added by a modifier).
    on_disk = {
        p.name for p in base.iterdir()
        if p.is_file() and p.suffix == ".py" and p.name != "_integrity.py"
    }
    for unexpected in sorted(on_disk - set(MANIFEST)):
        mismatches.append(f"  EXTRA    {unexpected}")

    return mismatches


def _emit_warning(mismatches: list[str]) -> None:
    """One warning block to stderr. Format is deliberately ugly so it
    doesn't blend into normal output — if you see this, the modules
    you're running aren't what we shipped."""
    sys.stderr.write(
        "\n"
        "⚠️  profine telemetry integrity check failed.\n"
        "    You're running a modified version of profine.telemetry.\n"
        "    Profine support may decline to help with bugs in modified clients.\n"
    )
    for line in mismatches:
        sys.stderr.write(line + "\n")
    sys.stderr.write(
        "    To silence: regenerate the manifest "
        f"(or unset {_DISABLE_ENV_VAR}=1 to disable the check).\n\n"
    )


# Run the check at import time. The result is also exposed via the
# `INTEGRITY_OK` module attribute so callers can branch on it (e.g.
# to mark the telemetry payload as "from a modified client").
_mismatches = verify_integrity()
INTEGRITY_OK: bool = not _mismatches
if _mismatches:
    _emit_warning(_mismatches)


__all__ = ["INTEGRITY_OK", "MANIFEST", "verify_integrity"]
