"""Deterministic runtime hooks for profiling.

These are universal monkey-patches that work on ANY PyTorch training script.
They capture step times, memory, loss, GPU utilization, and dataloader config
without needing to understand the script's structure.

The instrumented script (generated by the LLM) calls install_hooks() and
wraps training in a try/except StepLimitReached block.
"""

from __future__ import annotations

import json
import sys
import threading
import time
from dataclasses import dataclass, field
from typing import Any


class StepLimitReached(Exception):
    """Raised by StepController when the step budget is exhausted."""


def _all_optimizer_subclasses(base: type) -> list[type]:
    """Recursively find all subclasses of an optimizer base class."""
    result: list[type] = []
    work = list(base.__subclasses__())
    seen: set[type] = set()
    while work:
        cls = work.pop()
        if cls not in seen:
            seen.add(cls)
            result.append(cls)
            work.extend(cls.__subclasses__())
    return result


class StepController:
    """Hooks every optimizer.step() to count steps, measure time, sample memory."""

    def __init__(self, total_steps: int, wall_clock_limit_s: float = 900.0) -> None:
        import os
        # Executor sets these to override whatever the LLM wrote into the
        # instrumented install_hooks() call.
        step_override = os.environ.get("PROFINE_TOTAL_STEPS")
        wall_override = os.environ.get("PROFINE_WALL_CLOCK_LIMIT")
        self.total_steps = int(step_override) if step_override else total_steps
        self.wall_clock_limit_s = float(wall_override) if wall_override else wall_clock_limit_s
        # Probe-and-adapt: after this many steps we have a usable step-time
        # estimate and may lower total_steps to fit the wall-clock budget.
        self._probe_steps = int(os.environ.get("PROFINE_ADAPT_PROBE_STEPS", "3"))
        # Floor below which the sample count is statistically useless;
        # below this we'd rather take the wall-clock-cap fallback.
        self._adapt_floor = int(os.environ.get("PROFINE_ADAPT_MIN_STEPS", "10"))
        self._adapted: bool = False
        self.steps_completed = 0
        self.step_times_ms: list[float] = []
        self.memory_samples_bytes: list[int] = []
        self.wall_clock_expired = False
        self._last_step_end: float | None = None
        self._wall_start: float = time.perf_counter()
        self._profiler: Any = None
        self._loss_capture: LossCapture | None = None
        self._depth: int = 0  # reentrance guard for nested optimizer wrappers

    def set_profiler(self, profiler: Any) -> None:
        self._profiler = profiler

    def install(self) -> None:
        import torch
        self._originals: list[tuple[type, Any]] = []
        for cls in _all_optimizer_subclasses(torch.optim.Optimizer):
            if hasattr(cls, "step") and not getattr(cls.step, "_profine_hooked", False):
                original = cls.step
                self._originals.append((cls, original))
                controller = self

                def make_wrapper(orig):
                    def wrapped_step(self_opt, *args, **kwargs):
                        controller._before_step()
                        result = orig(self_opt, *args, **kwargs)
                        controller._after_step()
                        return result
                    wrapped_step._profine_hooked = True
                    return wrapped_step

                cls.step = make_wrapper(original)

    def uninstall(self) -> None:
        for cls, original in self._originals:
            cls.step = original
        self._originals.clear()

    def _before_step(self) -> None:
        self._depth += 1

    def _after_step(self) -> None:
        self._depth -= 1
        if self._depth > 0:
            return  # nested call (e.g. AcceleratedOptimizer wrapping real optimizer)

        import torch
        now = time.perf_counter()
        # Measure time between consecutive optimizer.step() calls —
        # captures the full iteration (forward + backward + optimizer),
        # not just the optimizer.step() duration.
        if self._last_step_end is not None:
            self.step_times_ms.append((now - self._last_step_end) * 1000)
        self._last_step_end = now

        if self._loss_capture is not None:
            self._loss_capture.flush_step()

        if torch.cuda.is_available():
            self.memory_samples_bytes.append(torch.cuda.max_memory_allocated())

        self.steps_completed += 1

        if self._profiler is not None:
            self._profiler.step()

        elapsed = time.perf_counter() - self._wall_start
        self._maybe_adapt(elapsed)
        if self.steps_completed >= self.total_steps:
            raise StepLimitReached(
                f"Completed {self.steps_completed}/{self.total_steps} steps"
            )
        if elapsed >= self.wall_clock_limit_s:
            self.wall_clock_expired = True
            raise StepLimitReached(
                f"Wall clock limit reached ({elapsed:.0f}s >= {self.wall_clock_limit_s:.0f}s) "
                f"after {self.steps_completed} steps"
            )

    def _maybe_adapt(self, elapsed: float) -> None:
        """Lower total_steps when the observed step time would otherwise
        blow the wall-clock budget."""
        if self._adapted or self.steps_completed < self._probe_steps:
            return
        # Median of inter-step times is robust to compile/cudagraph cold-start
        # outliers; fall back to elapsed-based mean when we don't yet have
        # enough samples (e.g. unit tests that drive _maybe_adapt directly).
        import statistics
        if len(self.step_times_ms) >= 2:
            avg_step_s = statistics.median(self.step_times_ms) / 1000.0
        else:
            avg_step_s = elapsed / self.steps_completed
        if avg_step_s <= 0:
            return
        # Even when the budget is already gone we propose the floor —
        # better than letting the wall-clock cap kill a step in flight.
        remaining_budget = max(0.0, self.wall_clock_limit_s - elapsed)
        fits = int(remaining_budget / avg_step_s)
        new_total = max(self._adapt_floor, self.steps_completed + fits)
        if new_total < self.total_steps:
            print(
                f"profine: avg step time ~{avg_step_s * 1000:.0f}ms — "
                f"reducing total_steps from {self.total_steps} to {new_total} "
                f"so the profile finishes inside the wall-clock budget."
            )
            self.total_steps = new_total
        self._adapted = True


class LossCapture:
    """Captures scalar loss values from backward() calls.

    Accumulates micro-batch losses and flushes the mean once per
    optimizer step (called by StepController).
    """

    def __init__(self) -> None:
        self.loss_values: list[float] = []  # one per optimizer step
        self._micro_losses: list[float] = []  # accumulator between steps
        self._original_backward: Any = None

    def flush_step(self) -> None:
        """Average accumulated micro-batch losses into one per-step value."""
        if self._micro_losses:
            self.loss_values.append(
                sum(self._micro_losses) / len(self._micro_losses)
            )
            self._micro_losses.clear()

    def install(self) -> None:
        import torch
        self._original_backward = torch.Tensor.backward
        capture = self

        original = self._original_backward

        def hooked_backward(tensor, *args, **kwargs):
            if tensor.dim() == 0:
                try:
                    capture._micro_losses.append(tensor.detach().item())
                except Exception:
                    pass
            return original(tensor, *args, **kwargs)

        torch.Tensor.backward = hooked_backward

    def uninstall(self) -> None:
        if self._original_backward is not None:
            import torch
            torch.Tensor.backward = self._original_backward
            self._original_backward = None


class GPUUtilizationSampler:
    """Samples GPU utilization at regular intervals via pynvml."""

    def __init__(self, interval_seconds: float = 0.1) -> None:
        self.interval = interval_seconds
        self.samples: list[float] = []
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None

    def install(self) -> None:
        try:
            import pynvml
            pynvml.nvmlInit()
            self._pynvml = pynvml
        except (ImportError, Exception):
            return

        self._thread = threading.Thread(target=self._sample_loop, daemon=True)
        self._thread.start()

    def _sample_loop(self) -> None:
        pynvml = self._pynvml
        try:
            count = pynvml.nvmlDeviceGetCount()
            handles = [pynvml.nvmlDeviceGetHandleByIndex(i) for i in range(count)]
        except Exception:
            return

        while not self._stop_event.is_set():
            try:
                utils = []
                for h in handles:
                    info = pynvml.nvmlDeviceGetUtilizationRates(h)
                    utils.append(info.gpu)
                self.samples.append(sum(utils) / len(utils) if utils else 0.0)
            except Exception:
                pass
            self._stop_event.wait(self.interval)

    def uninstall(self) -> None:
        self._stop_event.set()
        if self._thread is not None:
            self._thread.join(timeout=2.0)
        try:
            self._pynvml.nvmlShutdown()
        except Exception:
            pass


class DataLoaderCapture:
    """Captures DataLoader configuration kwargs."""

    def __init__(self) -> None:
        self.configs: list[dict[str, Any]] = []
        self._original_init: Any = None

    def install(self) -> None:
        try:
            from torch.utils.data import DataLoader
        except ImportError:
            return

        self._original_init = DataLoader.__init__
        capture = self
        original = self._original_init

        def hooked_init(dl_self, *args, **kwargs):
            capture.configs.append({
                "batch_size": kwargs.get("batch_size"),
                "num_workers": kwargs.get("num_workers", 0),
                "pin_memory": kwargs.get("pin_memory", False),
                "prefetch_factor": kwargs.get("prefetch_factor"),
                "persistent_workers": kwargs.get("persistent_workers", False),
                "shuffle": kwargs.get("shuffle", False),
            })
            return original(dl_self, *args, **kwargs)

        DataLoader.__init__ = hooked_init

    def uninstall(self) -> None:
        if self._original_init is not None:
            from torch.utils.data import DataLoader
            DataLoader.__init__ = self._original_init
            self._original_init = None


@dataclass
class HookContext:
    """Installs/uninstalls all profiler hooks and collects results."""
    step_controller: StepController
    loss_capture: LossCapture
    gpu_sampler: GPUUtilizationSampler
    dataloader_capture: DataLoaderCapture

    def install(self) -> None:
        self.loss_capture.install()
        self.gpu_sampler.install()
        self.dataloader_capture.install()
        self.step_controller._loss_capture = self.loss_capture
        self.step_controller.install()

    def uninstall(self) -> None:
        self.step_controller.uninstall()
        self.dataloader_capture.uninstall()
        self.gpu_sampler.uninstall()
        self.loss_capture.uninstall()

    def results(self) -> dict[str, Any]:
        import torch
        return {
            "steps_completed": self.step_controller.steps_completed,
            "step_times_ms": self.step_controller.step_times_ms,
            "memory_samples_bytes": self.step_controller.memory_samples_bytes,
            "memory_peak_bytes": (
                torch.cuda.max_memory_allocated() if torch.cuda.is_available() else 0
            ),
            "loss_values": self.loss_capture.loss_values,
            "gpu_utilization_samples": self.gpu_sampler.samples,
            "dataloader_configs": self.dataloader_capture.configs,
            "wall_clock_expired": self.step_controller.wall_clock_expired,
        }


_active_context: HookContext | None = None


def get_active_context() -> HookContext | None:
    """Return the currently active HookContext, if any."""
    return _active_context


def install_hooks(total_steps: int, wall_clock_limit_s: float = 900.0) -> HookContext:
    """Create and return a HookContext ready to install."""
    global _active_context
    ctx = HookContext(
        step_controller=StepController(total_steps, wall_clock_limit_s=wall_clock_limit_s),
        loss_capture=LossCapture(),
        gpu_sampler=GPUUtilizationSampler(),
        dataloader_capture=DataLoaderCapture(),
    )
    _active_context = ctx
    return ctx


# Sentinel printed by instrumented scripts so the executor can find results
RESULTS_SENTINEL = "__PROFINE_RESULTS__"


def emit_results(ctx: HookContext) -> None:
    """Print results as JSON for the executor to parse from stdout."""
    print(RESULTS_SENTINEL + json.dumps(ctx.results(), default=str))
